- name: Tomcat deployment playbook
  hosts: masters      
  become: yes               
  become_method: sudo       
  remote_user: root         
  vars:
    tomcat_ver: 9.0.30                          # Tomcat version to install and JDK  / 8.0.8 is deprecate 
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: Str0ngManagerP@ssw3rd      # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: Str0ngAdminP@ssw3rd          # UI admin password
  roles:
    - tomcat
